# This file is part of: React Development Template Stack 
# Copyright (c) 2024 Nico Jan Eelhart
#
# This source code is licensed under the MIT License found in the  'LICENSE.md' file in the root directory of this source tree.
#

#	Extending/Chaining 
#
#   Some notes regarding chaining:
#   NOTE 1
#   - Bind mounts don't carry over, you have to specify them again
#   - same counts for network and pretty much all items
#   - So better to use a common compose file and let the other compose files extend from items(like we done see extends: )

networks:
  react_network:                             # Define a network

volumes:
  react-vol:

services:
  webserver-nodejs_22-react:                 # Same name as base file!
    extends: 
      file: compose_nodejs_react_cont.yml    # our base compose file, see NOTE 1
      service: webserver-nodejs_22-react     # Same name as base file!
    build:
      context: .
      dockerfile: Dockerfile_Default_project_Cont
      args:
        PRJ_NAME_ARG: ${PRJ_NAME_ARG}
        PRJ_BASE_ARG: ${PRJ_BASE_ARG}
        PRJ_TYPE_ARG: ${PRJ_TYPE_ARG}
    environment:
       - PRJ_BASE=${PRJ_BASE}
    image: eelhart/react-base:latest2       # This name can be used to extend or chain this image.
    working_dir: ${PRJ_BASE_ARG}/$PRJ_NAME_ARG
    volumes:
#           - ./projects:/projects          # Bind mounts gave huge problems (No directory creation)
            - react-vol:/volume-share       # Alternative volume             
    command: ["npm", "start"]
#   command: ["/bin/sh", "-c", "while sleep 1000; do :; done"]  # use this in case of err, let's you get in(CMD)
# End compose file 


# build with:
#
# docker  compose -f compose_default_project.yml up -d  --remove-orphans --build --force-recreate 
#
# Alternative first build ben run
# docker-compose -f compose_default_project.yml build --no-cache
# docker-compose -f compose_default_project.yml up -d --remove-orphans --force-recreate


# Handies               
# docker system prune -a --volumes 
# docker logs  2dd65e02f0e4 
# docker exec -it 2dd65e02f0e4 /bin/bash
