# This file is part of: React Development Template Stack 
# Copyright (c) 2024 Nico Jan Eelhart
#
# This source code is licensed under the MIT License found in the  'LICENSE.md' file in the root directory of this source tree.
#

# This requires that the base image is build(docker  compose -f compose_nodejs_react_cont.yml up -d)
#	Extending/Chaining 
#
FROM eelhart/react-base:latest2

# Set the working directory
WORKDIR /projects

# Set arguments, made available via our compose file
ARG PRJ_NAME_ARG
ARG PRJ_BASE_ARG
ARG PRJ_TYPE_ARG

# Define build-time argument with default value
ARG PORT_ARG

# Use the build argument as an environment variable available at runtime
ENV PORT=${PORT_ARG}
EXPOSE ${PORT}

# Use the shell form explicitly to ensure environment variable expansion
RUN echo "Project Name 1: ${PRJ_BASE_ARG}/${PRJ_NAME_ARG}"
RUN /bin/sh -c "mkdir -p ${PRJ_BASE_ARG}"
RUN echo "Using port(Container and host):${PORT_ARG}" 


# Installs the npc tool globally on your system, don't think it needed (right?)
# RUN npm install -g create-react-app

# Remove the existing my-react-app directory if it exists. We don't want this
#RUN rm -rf $PRJ_BASE_ARG/${PRJ_NAME_ARG}



# Create the React app
WORKDIR ${PRJ_BASE_ARG}
#RUN npx create-react-app ${PRJ_NAME_ARG} --template cra-template || (echo "Failed to create React app"; exit 1)
RUN npx create-react-app ${PRJ_NAME_ARG} --template ${PRJ_TYPE_ARG}|| (echo "Failed to create React app"; exit 1)
COPY .env ${PRJ_BASE_ARG}/${PRJ_NAME_ARG}/.env




