# Base image nodejs React.
#
#	VERSION issues
#	Versions: 14, 15 un-comment 'RUN npm install'  		# Odd versions are not intended for release and development
#  	Versions: 16, 18, 20,22  and up. for these versions 'RUN npm install' needs to be commented

# Test against the following Node.js versions:
# (Don't leave comments at the end of the line = build error
#
# FROM node:16		# => Tested successful (July 2024)
# FROM node:18		# => Tested successful (July 2024)
# FROM node:20   	# => Tested successful (July 2024)
# FROM node:22  	# => Tested successful (July 2024)
#
# Default is the latest LTS version (as of July '24)
FROM node:22


WORKDIR /projects
# COPY . .

# Perhaps update here (TODO)
# RUN npm install
#


# ***** These instructions additional packages *** !!!
# INSTALL some required software -y makes sure defaults are applied during installation (always run apt-get update 1e )
RUN apt-get update && \
    apt-get install -y nano && \
	apt install net-tools -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Expose ports (Don't put behind the port on same line = error!)
EXPOSE 3001

